### ISSUE TITLE
002f-Como restaurante, deseo registrarme.

### ISSUE THREAD

**Issue by andlicon** [4GeeksAcademy/proyecto-final-app-restaurante#4]
![Image](https://github.com/4GeeksAcademy/proyecto-final-app-restaurante/assets/31941850/8363b317-ec59-41a4-87e1-aa849ab882c9)

1. **validar** password
    - [x] Contraseña longitud mínima 8 caracteres.
    - [x] Contraseña longitud máxima 20 carácteres.

2. **validar** email
    - [x] Debe ser un email válido.
    - [x] Acepta cualquier dominio.

3. **Función** handlerRegister
    - [x] llamar a restaurantRegister.

4. **Pagina** register restaurant debe estar en la ruta /register
    - [x] userPassword
    - [x] userEmail
    - [x] Phone number
    - [x] restaurantName
    - [x] restaurantRif
    - [x] Botón submit
    - [x] Al presionar el botón submit se debe ejecutar la función handlerRegister.
    - [x] debe ser un componente react controlado
 
5. **Flux Function** restaurantRegister.
    - [x] Fetch a "/restaurant".     POST
    - [ ] El body debe ser un objeto que contenga 2 objetos en su interior, uno con la información del user y otra con la información del restaurant.
    - [ ] El "name" del objeto user debe ser el rif del restaurant.
    - [x] De haber algún error, mostrar mensaje de error en consola.
    - [x] De ser exitoso, mostrar mensaje de éxito en consola.

**Comment by andlicon** [comment]
Ejemplo del body:
```
{
 "user":{
         "name": "Probando"
    }
    "restaurante" : {
        "name": "Probando"
    }
}
```

**Comment by jars4u** [comment]
Los 2 puntos pendientes en el subgrupo 5, fueron cambiados en discusiones grupales de proyecto
